const ActionTypes = {
    ADD_CARD: 'ADD_CARD',
    ADD_COLUMN: 'ADD_COLUMN',
    SEARCH_STRING: 'SEARCH_STRING',
    UPDATE_SEARCH: 'UPDATE_SEARCH',
    ADD_LIST: 'ADD_LIST',
    TOGGLE_CARD_FAVORITE: 'TOGGLE_CARD_FAVORITE',
};

export default ActionTypes;
